#!/bin/bash

runner=$1

dir=${BASH_SOURCE%/*}

for d in `ls -d $dir $dir/*/`
do
	for f in `ls $d/*.py`
	do
		echo "Running: ${runner} $f"
		${runner} --source=pyobs --omit=pyobs/setup.py $f
	done
done
