name: Build/Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7,3.8,'3.10.8']

    steps: 

    - name: Setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Clone pyobs
      uses: actions/checkout@v2
      with:
        path: pyobs

    - name: Install pyobs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy coverage
        pip install ./pyobs
        cd pyobs
        python setup.py build_ext
        python setup.py clean	

    - name: Test
      run: |
        export PYTHONPATH=$PWD/pyobs/
        cd pyobs
        ./tests/run "coverage run -p"

    - name: Coverage report
      run: |
        cd pyobs
        coverage combine
        coverage report -m  # Print coverage report to screen
        coverage xml  # Export coverage report as XML file, for codecov.i

    - name: Upload coverage to Codecov
      if: matrix.python-version == 3.6
      env:
        PYTHON_VERSION: python${{ matrix.python-version }}
        CODECOV_TOKEN: "6f56ccbf-ceab-4666-81a7-fc2431ba9bb8"
        CODECOV_ENV: PYTHON_VERSION, CODECOV_TOKEN
      run: |
        cd pyobs
        bash <(curl -s https://codecov.io/bash) -f ./coverage.xml

