name: Build/Test MacOS

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]

    steps: 

    - name: Setup python 3.8 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
        architecture: x64

    - name: Clone pyobs
      uses: actions/checkout@v2
      with:
        path: pyobs

    - name: Install pyobs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy coverage
        pip install ./pyobs

    - name: Test
      run: |
        export PYTHONPATH=$PWD/pyobs/
        cd pyobs
        ./tests/run "coverage run -p"

